# Generated by Django 3.2.6 on 2021-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grdnr_server', '0002_auto_20211030_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigningjobsmodel',
            name='task_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
