# Generated by Django 3.2.6 on 2021-11-15 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grdnr_server', '0004_accountsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactionHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('None', 'None'), ('Debit', 'Debit'), ('Credit', 'Credit')], default='None', max_length=100)),
                ('transaction_amount', models.CharField(blank=True, max_length=100)),
                ('transaction_description', models.CharField(max_length=200)),
                ('transaction_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('transaction_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online Transfer', 'Online Transfer'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='None', max_length=100)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grdnr_server.accountsmodel')),
                ('assign_task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grdnr_server.assigningjobsmodel')),
                ('grdnr_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grdnr_server.grdnrsmodel')),
            ],
        ),
    ]
