# Generated by Django 3.2.6 on 2021-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrdnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grdn_id', models.CharField(max_length=100)),
                ('grdn_name', models.CharField(max_length=200)),
                ('grdn_location', models.CharField(max_length=500)),
                ('grdn_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrdnrModel',
            fields=[
                ('grdnr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grdnr_name', models.CharField(max_length=100)),
                ('grdnr_password', models.CharField(max_length=50)),
                ('grdnr_phone', models.CharField(max_length=50)),
                ('grdnr_address', models.CharField(blank=True, max_length=100)),
                ('grdnr_profile_photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_pcr_report', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_vaccination_id', models.CharField(blank=True, max_length=50)),
                ('grdnr_vaccination_status', models.CharField(blank=True, max_length=50)),
                ('grdnr_skills', models.CharField(blank=True, max_length=100)),
                ('grdnr_profession', models.CharField(blank=True, max_length=100)),
                ('grdnr_language', models.CharField(blank=True, max_length=100)),
                ('grdnr_resignation_date', models.DateField(blank=True)),
                ('grdnr_joining_date', models.DateField(blank=True)),
                ('grdnr_emirates_id_front', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_emirates_id_back', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_visa_copy', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_driving_licence_front', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_driving_licence_back', models.ImageField(blank=True, upload_to='uploads/')),
                ('grdnr_account_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_file', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=100)),
                ('task_detail', models.CharField(max_length=500)),
                ('task_value', models.CharField(max_length=50)),
                ('task_status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
